### list messages
GET  http://localhost:3000/messages

### create a message
POST http://localhost:3000/messages
Content-Type: application/json

{
  "content" : "message six"
}

### get a message by id
GET http://localhost:3000/messages/322